# Generated by Django 4.2.3 on 2023-08-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='отрасль права')),
            ],
            options={
                'verbose_name': 'раздел права',
                'verbose_name_plural': 'разделы права',
            },
        ),
        migrations.CreateModel(
            name='LegalApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_assistance', models.CharField(choices=[('need consultation', 'юридическая консультация'), ('need participation', 'участие в юридическом мероприятии'), ('need docs', 'составление юридических документов'), ('another', 'иное')], max_length=50, verbose_name='тип юридической помощи')),
                ('place_of_assistance', models.CharField(blank=True, choices=[('place of lawyer', 'помощь по месту нахождения юриста'), ('place of client', 'помомщь по месту нахождения клиента')], max_length=50, verbose_name='место получения юридической помощи')),
                ('note_of_application', models.TextField(verbose_name='пояснения клиента')),
                ('status', models.CharField(choices=[('application is accepted', 'заявка принята'), ('search for a lawyer', 'осуществляется поиск юриста'), ('on the way', 'в дороге'), ('assistance is provided', 'помощь оказывается'), ('assistance completed', 'оказание юридической помощи окончено'), ('open dispute', 'открыт диспут'), ('application ended', 'заявка закрыта')], default='application is accepted', max_length=150, verbose_name='статус заявки')),
                ('authority', models.CharField(blank=True, max_length=150, verbose_name='орган власти, в котором необходимо представлять интересы клиента')),
                ('geolocation', models.CharField(blank=True, max_length=100, verbose_name='Координаты нахождения заказчика')),
            ],
            options={
                'verbose_name': 'Заявка на юридическую помощь',
                'verbose_name_plural': 'Заявки на скорую юридическую помощь',
                'ordering': ['client'],
            },
        ),
    ]
