# Generated by Django 4.2.3 on 2023-08-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legalApplication', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalapp',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.clientuserinterface', verbose_name='заказчик'),
        ),
        migrations.AddField(
            model_name='legalapp',
            name='lawer',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.PROTECT, to='usersApp.lawyeruserinterface'),
        ),
        migrations.AddField(
            model_name='legalapp',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersApp.fieldsoflaw', to_field='area', verbose_name='специализация'),
        ),
        migrations.AddField(
            model_name='legalapp',
            name='type_of_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legalApplication.lawtype', to_field='name', verbose_name='область права'),
        ),
    ]
