# Generated by Django 4.2.3 on 2023-08-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
        ('legalApplication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalapp',
            name='lawer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usersApp.lawyeruserinterface'),
        ),
    ]
