# Generated by Django 4.2.3 on 2023-08-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legalApplication', '0003_alter_legalapp_lawer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalapp',
            old_name='lawer',
            new_name='lawyer',
        ),
    ]
