# Generated by Django 4.2.3 on 2023-08-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalApplication', '0005_legalapp_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalapp',
            name='city',
            field=models.CharField(max_length=100, verbose_name='город, в котором необходима помощь'),
        ),
    ]
