# Generated by Django 4.2.3 on 2023-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyeruserinterface',
            name='incompetence',
            field=models.ManyToManyField(db_table='lawyersIncompetence', to='usersApp.fieldsoflaw'),
        ),
    ]
