# Generated by Django 4.2.3 on 2023-08-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_legalappadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalAppAdmin',
        ),
    ]
