# Generated by Django 4.2.3 on 2023-08-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_alter_lawyeruserinterface_incompetence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['kind_of_user', 'username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Все пользователи'},
        ),
    ]
