# Generated by Django 4.2.3 on 2023-08-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_alter_lawyeruserinterface_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Все пользователи'},
        ),
    ]
