# Generated by Django 4.2.3 on 2023-08-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuserinterface',
            name='email_confirm',
        ),
        migrations.RemoveField(
            model_name='lawyeruserinterface',
            name='email_confirm',
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
