# Generated by Django 4.2.3 on 2023-08-29 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usersApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_delete_legalappadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyeruserinterface',
            name='name_of_interface',
            field=models.ForeignKey(default=usersApp.models.LawyerUserInterface.get_default_type_user, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_user_interface', to='usersApp.userskind', verbose_name='тип пользователя'),
        ),
        migrations.AlterField(
            model_name='lawyeruserinterface',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_user_interface', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='пользователь'),
        ),
    ]
