# Generated by Django 4.2.3 on 2023-08-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientuserinterface',
            options={'ordering': ['user_name', 'full_name'], 'verbose_name': 'Пользователь-клиент', 'verbose_name_plural': 'Пользователи-клиенты'},
        ),
        migrations.AlterModelOptions(
            name='fieldsoflaw',
            options={'ordering': ['type', 'area'], 'verbose_name': 'Отрасль', 'verbose_name_plural': 'Отрасли права'},
        ),
        migrations.AlterModelOptions(
            name='lawyeruserinterface',
            options={'ordering': ['is_advokat', 'user_name', 'full_name'], 'verbose_name': 'Пользователь-юрист', 'verbose_name_plural': 'Пользователи-юристы'},
        ),
    ]
