# Generated by Django 4.2.3 on 2023-08-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_alter_clientuserinterface_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyeruserinterface',
            name='specialization',
            field=models.ManyToManyField(blank=True, db_table='lawyersSpecialization', related_name='lawyer_specialization', to='usersApp.fieldsoflaw'),
        ),
    ]
