# Generated by Django 4.2.3 on 2023-08-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0005_alter_lawyeruserinterface_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kind_of_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersApp.userskind', to_field='name', verbose_name='тип пользователя'),
        ),
    ]
